In [4]:
import numpy as np
import pandas as pd
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split

In [5]:
train = pd.read_csv('train.csv')

In [7]:
train.isnull().sum()

ID         0
crim       0
zn         0
indus      0
chas       0
nox        0
rm         0
age        0
dis        0
rad        0
tax        0
ptratio    0
black      0
lstat      0
medv       0
dtype: int64

In [8]:
test = pd.read_csv('test.csv')

In [9]:
test.isnull().sum()

ID         0
crim       0
zn         0
indus      0
chas       0
nox        0
rm         0
age        0
dis        0
rad        0
tax        0
ptratio    0
black      0
lstat      0
dtype: int64

In [10]:
train.head()

,ID,crim,zn,indus,chas,nox,rm,age,dis,rad,tax,ptratio,black,lstat,medv
0,1,0.00632,18.0,2.31,0,0.538,6.575,65.2,4.0900,1,296,15.3,396.90,4.98,24.0
1,2,0.02731,0.0,7.07,0,0.469,6.421,78.9,4.9671,2,242,17.8,396.90,9.14,21.6
2,4,0.03237,0.0,2.18,0,0.458,6.998,45.8,6.0622,3,222,18.7,394.63,2.94,33.4
3,5,0.06905,0.0,2.18,0,0.458,7.147,54.2,6.0622,3,222,18.7,396.90,5.33,36.2
4,7,0.08829,12.5,7.87,0,0.524,6.012,66.6,5.5605,5,311,15.2,395.60,12.43,22.9

In [15]:
x = ['ID','crim','zn','indus','chas','nox','age','dis','rad','tax','ptratio','black','lstat']

In [16]:
xx = train[x]

In [17]:
y = ['medv']

In [18]:
yy = train[y]

In [20]:
xtrain,xtest,ytrain,ytest = train_test_split(xx,yy,test_size=0.2,random_state=40)

In [22]:
clf = LinearRegression()

In [86]:
clf.fit(xtrain,ytrain)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False)

In [87]:
clf.score(xtrain,ytrain)

0.6821033125307054

In [88]:
a = ['ID','crim','zn','indus','chas','nox','age','dis','rad','tax','ptratio','black','lstat']

In [89]:
aa = test[a]

In [90]:
p =clf.predict(aa)

In [91]:
test.ID.head()

0     3
1     6
2     8
3     9
4    10
Name: ID, dtype: int64

In [104]:
test.ID.isnull().sum()

0

In [103]:
qq = p.ravel()
qq

array([28.93886294, 25.90149058, 17.9620748 ,  8.77363084, 18.13944861,
       17.15138978, 20.60815794, 15.85107054, 14.56174255, 16.31238416,
       18.58387171, 19.44019911,  5.40775152, 14.96968446, 26.13567404,
       24.34828198, 25.2453756 , 26.39132373,  6.63057975, 27.73800992,
       23.12085771, 25.05387129, 21.55508238, 21.81628809, 19.9209094 ,
       23.29437786, 27.15085425, 28.13262794, 30.40932313, 28.49001347,
       31.24236847, 30.92328059, 29.31888434, 22.08149047, 19.39667205,
       20.10713084, 21.10807387, 20.07780585, 20.71063311, 23.99524625,
       14.66130567, 19.23933278, 19.95280314, 15.60938748, 10.43138777,
       11.63655135,  9.38195665, 17.50631205, 21.74319379, 26.93654284,
       21.7457511 , 33.50792265, 40.12875345, 27.00705777, 25.5457464 ,
       25.20744135, 33.52928161, 39.24448167, 35.07130989, 33.00961179,
       29.85471867, 35.08982759, 17.46844465, 19.33012071, 23.9525493 ,
       24.57464927, 24.74177707, 27.9412211 , 26.83898508, 32.0284288 ,
       33.9412391 , 31.69217924, 31.26113852, 30.74119267, 28.44642168,
       28.14344609, 24.27758922, 13.01790131, 19.77292398, 22.22131948,
       25.67496497, 23.20610139, 37.49877367, 37.87362851, 35.69856004,
       36.29391672, 35.64666386, 28.80724072, 23.44970297, 35.03271585,
       36.06241426, 37.07513159, 31.55772037, 35.90800687, 28.5678902 ,
       26.19601541, 35.41741469, 24.22669682, 26.54580492, 30.50975221,
       30.51787474, 30.37347871, 33.80778767, 26.61848446, 24.946367  ,
       20.73334603, 24.99692174, 23.86971946, 20.98299999, 23.39892455,
       22.33492379, 20.41817072, 23.82762571, 21.0315476 , 20.1200671 ,
       14.69698472, 12.80958627, 19.26758776, 19.01878873, 25.83836761,
       16.58301348, 18.51989063, 19.26246144, 24.07974967, 32.70068594,
       37.04413578, 23.57352754, 14.7771298 , 16.60477667, 17.75398404,
       17.00790407,  8.52620404,  8.27512114, 19.20667574, 21.0652703 ,
       19.65261123, 17.55270147,  8.45931949, 17.01125509,  9.38916295,
       13.28174216, 15.56340903, 17.5906191 , 22.8201763 , 14.97163399,
        3.81383884,  8.89221057, 19.89854993, 19.35622384, 21.88323554,
       11.61670676, 18.00137319, 17.49356395, 10.10264601, 13.76006508,
        1.17015577, 16.82442472, 15.72265103, 14.13760806, 12.74729208,
       12.40682682, 19.72381737, 23.30239957, 14.08177729, 27.35964871,
       21.83651793,  5.69939624, 20.14170562, 15.71685823, 13.73558806,
       21.11282901, 20.07539807, 25.46624298])

In [105]:
sub = pd.DataFrame({'ID':test.ID,'medv':qq})

In [106]:
sub.to_csv('noob.csv',index=False)

In [108]:
sub.shape

(173, 2)

In [113]:
train.info

<bound method DataFrame.info of       ID      crim    zn  indus  chas    nox     rm    age     dis  rad  tax  \
0      1   0.00632  18.0   2.31     0  0.538  6.575   65.2  4.0900    1  296
1      2   0.02731   0.0   7.07     0  0.469  6.421   78.9  4.9671    2  242
2      4   0.03237   0.0   2.18     0  0.458  6.998   45.8  6.0622    3  222
3      5   0.06905   0.0   2.18     0  0.458  7.147   54.2  6.0622    3  222
4      7   0.08829  12.5   7.87     0  0.524  6.012   66.6  5.5605    5  311
5     11   0.22489  12.5   7.87     0  0.524  6.377   94.3  6.3467    5  311
6     12   0.11747  12.5   7.87     0  0.524  6.009   82.9  6.2267    5  311
7     13   0.09378  12.5   7.87     0  0.524  5.889   39.0  5.4509    5  311
8     14   0.62976   0.0   8.14     0  0.538  5.949   61.8  4.7075    4  307
9     15   0.63796   0.0   8.14     0  0.538  6.096   84.5  4.4619    4  307
10    16   0.62739   0.0   8.14     0  0.538  5.834   56.5  4.4986    4  307
11    17   1.05393   0.0   8.14     0  0.538  5.935   29.3  4.4986    4  307
12    19   0.80271   0.0   8.14     0  0.538  5.456   36.6  3.7965    4  307
13    21   1.25179   0.0   8.14     0  0.538  5.570   98.1  3.7979    4  307
14    22   0.85204   0.0   8.14     0  0.538  5.965   89.2  4.0123    4  307
15    23   1.23247   0.0   8.14     0  0.538  6.142   91.7  3.9769    4  307
16    24   0.98843   0.0   8.14     0  0.538  5.813  100.0  4.0952    4  307
17    28   0.95577   0.0   8.14     0  0.538  6.047   88.8  4.4534    4  307
18    31   1.13081   0.0   8.14     0  0.538  5.713   94.1  4.2330    4  307
19    32   1.35472   0.0   8.14     0  0.538  6.072  100.0  4.1750    4  307
20    35   1.61282   0.0   8.14     0  0.538  6.096   96.9  3.7598    4  307
21    39   0.17505   0.0   5.96     0  0.499  5.966   30.2  3.8473    5  279
22    40   0.02763  75.0   2.95     0  0.428  6.595   21.8  5.4011    3  252
23    41   0.03359  75.0   2.95     0  0.428  7.024   15.8  5.4011    3  252
24    43   0.14150   0.0   6.91     0  0.448  6.169    6.6  5.7209    3  233
25    44   0.15936   0.0   6.91     0  0.448  6.211    6.5  5.7209    3  233
26    45   0.12269   0.0   6.91     0  0.448  6.069   40.0  5.7209    3  233
27    46   0.17142   0.0   6.91     0  0.448  5.682   33.8  5.1004    3  233
28    47   0.18836   0.0   6.91     0  0.448  5.786   33.3  5.1004    3  233
29    48   0.22927   0.0   6.91     0  0.448  6.030   85.5  5.6894    3  233
..   ...       ...   ...    ...   ...    ...    ...    ...     ...  ...  ...
303  465   7.83932   0.0  18.10     0  0.655  6.209   65.4  2.9634   24  666
304  466   3.16360   0.0  18.10     0  0.655  5.759   48.2  3.0665   24  666
305  467   3.77498   0.0  18.10     0  0.655  5.952   84.7  2.8715   24  666
306  468   4.42228   0.0  18.10     0  0.584  6.003   94.5  2.5403   24  666
307  469  15.57570   0.0  18.10     0  0.580  5.926   71.0  2.9084   24  666
308  470  13.07510   0.0  18.10     0  0.580  5.713   56.7  2.8237   24  666
309  472   4.03841   0.0  18.10     0  0.532  6.229   90.7  3.0993   24  666
310  473   3.56868   0.0  18.10     0  0.580  6.437   75.0  2.8965   24  666
311  475   8.05579   0.0  18.10     0  0.584  5.427   95.4  2.4298   24  666
312  477   4.87141   0.0  18.10     0  0.614  6.484   93.6  2.3053   24  666
313  478  15.02340   0.0  18.10     0  0.614  5.304   97.3  2.1007   24  666
314  479  10.23300   0.0  18.10     0  0.614  6.185   96.7  2.1705   24  666
315  480  14.33370   0.0  18.10     0  0.614  6.229   88.0  1.9512   24  666
316  481   5.82401   0.0  18.10     0  0.532  6.242   64.7  3.4242   24  666
317  482   5.70818   0.0  18.10     0  0.532  6.750   74.9  3.3317   24  666
318  484   2.81838   0.0  18.10     0  0.532  5.762   40.3  4.0983   24  666
319  485   2.37857   0.0  18.10     0  0.583  5.871   41.9  3.7240   24  666
320  487   5.69175   0.0  18.10     0  0.583  6.114   79.8  3.5459   24  666
321  488   4.83567   0.0  18.10     0  0.583  5.905   53.2  3.1523   24  666
322  489   0.15086   0.0  27.74     0  0.609  5.454   92.7  1.8209    4  711
323  491   0.20746   0.0  27.74     0  0.609  5.093   98.0  1.8226    4  711
324  492   0.10574   0.0  27.74     0  0.609  5.983   98.8  1.8681    4  711
325  493   0.11132   0.0  27.74     0  0.609  5.983   83.5  2.1099    4  711
326  494   0.17331   0.0   9.69     0  0.585  5.707   54.0  2.3817    6  391
327  498   0.26838   0.0   9.69     0  0.585  5.794   70.6  2.8927    6  391
328  500   0.17783   0.0   9.69     0  0.585  5.569   73.5  2.3999    6  391
329  502   0.06263   0.0  11.93     0  0.573  6.593   69.1  2.4786    1  273
330  503   0.04527   0.0  11.93     0  0.573  6.120   76.7  2.2875    1  273
331  504   0.06076   0.0  11.93     0  0.573  6.976   91.0  2.1675    1  273
332  506   0.04741   0.0  11.93     0  0.573  6.030   80.8  2.5050    1  273

     ptratio   black  lstat  medv
0       15.3  396.90   4.98  24.0
1       17.8  396.90   9.14  21.6
2       18.7  394.63   2.94  33.4
3       18.7  396.90   5.33  36.2
4       15.2  395.60  12.43  22.9
5       15.2  392.52  20.45  15.0
6       15.2  396.90  13.27  18.9
7       15.2  390.50  15.71  21.7
8       21.0  396.90   8.26  20.4
9       21.0  380.02  10.26  18.2
10      21.0  395.62   8.47  19.9
11      21.0  386.85   6.58  23.1
12      21.0  288.99  11.69  20.2
13      21.0  376.57  21.02  13.6
14      21.0  392.53  13.83  19.6
15      21.0  396.90  18.72  15.2
16      21.0  394.54  19.88  14.5
17      21.0  306.38  17.28  14.8
18      21.0  360.17  22.60  12.7
19      21.0  376.73  13.04  14.5
20      21.0  248.31  20.34  13.5
21      19.2  393.43  10.13  24.7
22      18.3  395.63   4.32  30.8
23      18.3  395.62   1.98  34.9
24      17.9  383.37   5.81  25.3
25      17.9  394.46   7.44  24.7
26      17.9  389.39   9.55  21.2
27      17.9  396.90  10.21  19.3
28      17.9  396.90  14.15  20.0
29      17.9  392.74  18.80  16.6
..       ...     ...    ...   ...
303     20.2  396.90  13.22  21.4
304     20.2  334.40  14.13  19.9
305     20.2   22.01  17.15  19.0
306     20.2  331.29  21.32  19.1
307     20.2  368.74  18.13  19.1
308     20.2  396.90  14.76  20.1
309     20.2  395.33  12.87  19.6
310     20.2  393.37  14.36  23.2
311     20.2  352.58  18.14  13.8
312     20.2  396.21  18.68  16.7
313     20.2  349.48  24.91  12.0
314     20.2  379.70  18.03  14.6
315     20.2  383.32  13.11  21.4
316     20.2  396.90  10.74  23.0
317     20.2  393.07   7.74  23.7
318     20.2  392.92  10.42  21.8
319     20.2  370.73  13.34  20.6
320     20.2  392.68  14.98  19.1
321     20.2  388.22  11.45  20.6
322     20.1  395.09  18.06  15.2
323     20.1  318.43  29.68   8.1
324     20.1  390.11  18.07  13.6
325     20.1  396.90  13.35  20.1
326     19.2  396.90  12.01  21.8
327     19.2  396.90  14.10  18.3
328     19.2  395.77  15.10  17.5
329     21.0  391.99   9.67  22.4
330     21.0  396.90   9.08  20.6
331     21.0  396.90   5.64  23.9
332     21.0  396.90   7.88  11.9

[333 rows x 15 columns]>